### ISSUE TITLE
关于优化翻译流程的建议

### ISSUE THREAD

**Issue by hao-lee** [hust-open-atom-club/linux-insides-zh#100]
我和 @mudongliang [所想的一致](https://github.com/MintCN/linux-insides-zh/issues/5#issuecomment-260970881)。
* 每个志愿者翻译某一节时可以在本节的开头注明此时此刻所对应的上游commit七位短sha1值。
* 志愿者除了翻译任务之外，又延伸出了一项新任务，就是隔几天把翻译版本注明的sha1值和上游此文件最新commit的sha1值进行比对，从而检查出每个文件是否过期。
* 这样一来每个文件的状态除了[未开始][正在进行][已完成]之外，就又多了两种状态[待更新][最新]，由志愿者及时更新章节的状态。

以这种方式来进行翻译的话可以使翻译流程更为清晰，也可以使已翻译完成的章节获得及时的修正和更新。

不知大家觉得这种方式怎么样。

**Comment by mudongliang** [comment]
@hao-lee 我觉得挺好

**Comment by mudongliang** [comment]
@hao-lee 我会先将每一个章节的 README 先尝试这样做，看看效果。

**Comment by mudongliang** [comment]
@hao-lee @xinqiu 我在[我的 fork 库](https://github.com/mudongliang/linux-insides-zh)中尝试了给 Booting/README.md 加上该文件最新的 commit 号。***注意***，是该文件最新的 commit ，而不是整个库最新的 commit ，因为很多后续的 commits 和这个文件无关。
所以，只要我们发现我们标注的 commit 不是最新的话，那就直接查看那个文件对应的 commit ，然后把上游修改的部分回馈到我们的中文库就 OK 了。
大家以为如何？

**Comment by hao-lee** [comment]
就是这样~注明该文件最新commit，这样定期检查一次就能知道哪些文件被上游更新过了。

**Comment by mudongliang** [comment]
目前只是将所有的 README 文件加上了对应的 commit id，至于其他章节，可能需要大家提交翻译的时候，慢慢维护了，这个事情得慢慢来。

**Comment by mudongliang** [comment]
@hao-lee @xinqiu 对于那些尚未开始翻译的英文原文文件，我会设立一个计划，定期更新它与上游保持，同时keep 对应的版本号；但是这些文章被翻译，就可以直接使用keep 的版本号与上游保持对应。你们觉得如何？

**Comment by hao-lee** [comment]
@mudongliang 每个文件都单独追踪还是全部作为一个整体打版本号呢

**Comment by mudongliang** [comment]
Every file has its git history. Just track file one by one.

**Comment by hao-lee** [comment]
可以试试再说

**Comment by mudongliang** [comment]
@xinqiu 我们可能需要将库里面目前所有已经翻译过的文件全部进行检查一下，和上游最新的版本进行比较。没有什么问题的话，就可以直接更新表格中对应的内容。如果有问题的话，我们可能需要加上一个任务，就是更新文件翻译的操作。另外，这个工作我会在新添加一个Issue

**Comment by mudongliang** [comment]
或者我们直接抽时间，把所有的已翻译的文章进行更新。

**Comment by xinqiu** [comment]
你是说和英文原版进行比对么？

**Comment by hao-lee** [comment]
的确，翻译到现在其实已经有些混乱了，而且英文版里面还有很多错误之处，接下来的工作难度不小

**Comment by mudongliang** [comment]
@hao-lee @xinqiu 我在 README 中列出来我们后面需要做的工作。确实挺艰难的，任务也很多。所以，我们要花大力气去 check 原来已经翻译的版本，同时规范新的翻译。

**Comment by xinqiu** [comment]
可是我有个疑惑的地方，我们没有在翻译时，做上当前版本的标记，所以现在来检查翻译好的文件与上游最新文件直接的差别，是不是要进行中英文的比较？

**Comment by mudongliang** [comment]
这就是早期没有规范好所导致的问题。没有办法作为维护者，这些 dirty work 没有帮忙的话，只能是我们两个干了

**Comment by hao-lee** [comment]
而且涉及的子系统太多了，一不小心就造成翻译不准确或翻译错误

**Comment by xinqiu** [comment]
只能一个个文件与最新的进行比对翻译了，相当于看看最新的是否添加了一些当前翻译没有的地方。

**Comment by mudongliang** [comment]
所以这个事情越早做越有利。

**Comment by kele1997** [comment]
部分维基百科的条目存在中文版本，文章中的地址是放中文还是放英文比较好？

**Comment by hao-lee** [comment]
@kele1997 维基百科中文版和英文版不同步，没什么人去翻译，繁体还好点。

**Comment by xindoo** [comment]
有没有人考虑整理一个专业术语表，否则这么多人翻译，可能有些术语会被翻译成不同的中文

**Comment by mudongliang** [comment]
https://github.com/LCTT/TranslateProject/blob/master/Dict.md

以上是LCTT 的专业术语翻译列表。我们可以把我们遇见的单词放到这里，以及参与维护这个列表

**Comment by mudongliang** [comment]
#255 ChatGPT 会是一个很不错的工具，来帮助我们优化翻译流程
