### ISSUE TITLE
内核引导过程. 第一部分--- 0x10ffef 变成有 A20 缺陷的 0x00ffef

### ISSUE THREAD

**Issue by Shawn20162016** [hust-open-atom-club/linux-insides-zh#226]
"0x10ffef 变成有 A20 缺陷的 0x00ffef" 缺陷一词令人费解，可考虑翻译为：

0x10ffef 变成 0x00ffef， 这里A20(地址线21bit)溢出，被置0。

**Comment by Shawn20162016** [comment]
“得到的 0xfffffff0 是 4GB - 16 字节。”

这是一个地址，考虑翻译为 得到的 0xfffffff0 是 位于"4GB - 16 字节"处的地址。

**Comment by mudongliang** [comment]
请提交PR，谢谢！
