### ISSUE TITLE
Bootting linux-bootstrap-2.md 线性地址引用图片显示失败，参见正文

### ISSUE THREAD

**Issue by oracode-600** [hust-open-atom-club/linux-insides-zh#261]
![image](https://github.com/hust-open-atom-club/linux-insides-zh/assets/27880619/502b521e-5f8c-4f3f-8889-e2a31f73022c)

**Comment by mudongliang** [comment]
谢谢报告这个问题，我看到上游已经使用了自己仓库中的图片。我们会尽快做一次整体内容的迁移。

**Comment by mudongliang** [comment]
fixed by commit 612ac5c
