### ISSUE TITLE
http://x86.renejeschke.de/ is down, we need to find an alternative website

### ISSUE THREAD

**Issue by mudongliang** [hust-open-atom-club/linux-insides-zh#283]

**Comment by Souls-R** [comment]
根据[webarchive](https://web.archive.org/web/20170605132607/http://x86.renejeschke.de/html/file_module_x86_id_41.html)，
源仓库应该是https://github.com/rjeschke/x86.renejeschke.de ，或许可以用github pages托管一份

**Comment by mudongliang** [comment]
可以这么做，我们fork一份，然后 github page 转发到 x86.hust.openatom.club。

**Comment by mudongliang** [comment]
https://x86.hust.openatom.club/ 已上线，多谢 @Souls-R
